/**
 * Generate M3 HCT palette — uses createRequire workaround for Node 24 ESM.
 */
import { createRequire } from 'module'
const require = createRequire(import.meta.url)

// Patch the broken import by pre-requiring it
const dynamicColorPath = new URL(
  '../node_modules/@material/material-color-utilities/dynamiccolor/dynamic_color.js',
  import.meta.url
).pathname.replace(/^\/([A-Z]:)/, '$1')  // Fix Windows path

// Force CJS resolution
process.env.NODE_PATH = new URL('../node_modules', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')

const {
  argbFromHex,
  hexFromArgb,
  TonalPalette,
  Hct,
} = require('@material/material-color-utilities')

// ── Seed colors ─────────────────────────────────────────────────────────
const seeds = {
  primary:   '#7c5cfc',
  secondary: '#2dd4bf',
  tertiary:  '#fb923c',
  error:     '#f04545',
  neutral:   '#7c5cfc',  // neutral derived from primary in M3
}

function palette(hex) {
  return TonalPalette.fromHct(Hct.fromInt(argbFromHex(hex)))
}
function t(p, tone) { return hexFromArgb(p.tone(tone)) }

const pp = palette(seeds.primary)
const sp = palette(seeds.secondary)
const tp = palette(seeds.tertiary)
const ep = palette(seeds.error)
// Neutral: desaturated version of primary (M3 uses same hue, much lower chroma)
const np = TonalPalette.fromHct(Hct.from(
  Hct.fromInt(argbFromHex(seeds.primary)).hue,
  4,   // very low chroma = near-gray with primary hue
  50
))
const nvp = TonalPalette.fromHct(Hct.from(
  Hct.fromInt(argbFromHex(seeds.primary)).hue,
  8,   // slightly more chroma for neutral-variant
  50
))

// M3 Dark scheme role mapping (tone values from M3 spec)
const roles = {
  // Primary
  'primary':              t(pp, 80),
  'on-primary':           t(pp, 20),
  'primary-container':    t(pp, 30),
  'on-primary-container': t(pp, 90),
  'primary-fixed':        t(pp, 90),
  'primary-fixed-dim':    t(pp, 80),

  // Secondary
  'secondary':              t(sp, 80),
  'on-secondary':           t(sp, 20),
  'secondary-container':    t(sp, 30),
  'on-secondary-container': t(sp, 90),

  // Tertiary
  'tertiary':              t(tp, 80),
  'on-tertiary':           t(tp, 20),
  'tertiary-container':    t(tp, 30),
  'on-tertiary-container': t(tp, 90),

  // Error
  'error':              t(ep, 80),
  'on-error':           t(ep, 20),
  'error-container':    t(ep, 30),
  'on-error-container': t(ep, 90),

  // Surface (dark — we push surface darker than M3 default tone 6)
  'surface-dim':                    t(np, 6),
  'surface':                        t(np, 6),
  'surface-bright':                 t(np, 24),
  'surface-container-lowest':       t(np, 4),
  'surface-container-low':          t(np, 10),
  'surface-container':              t(np, 12),
  'surface-container-high':         t(np, 17),
  'surface-container-highest':      t(np, 22),
  'on-surface':                     t(np, 90),
  'on-surface-variant':             t(nvp, 80),
  'outline':                        t(nvp, 60),
  'outline-variant':                t(nvp, 30),
  'inverse-surface':                t(np, 90),
  'inverse-on-surface':             t(np, 20),
  'inverse-primary':                t(pp, 40),
  'scrim':                          t(np, 0),
  'shadow':                         t(np, 0),

  // Primary palette tones (for direct use)
  'primary-palette-5':   t(pp, 5),
  'primary-palette-10':  t(pp, 10),
  'primary-palette-15':  t(pp, 15),
  'primary-palette-20':  t(pp, 20),
  'primary-palette-30':  t(pp, 30),
  'primary-palette-40':  t(pp, 40),
  'primary-palette-50':  t(pp, 50),
  'primary-palette-60':  t(pp, 60),
  'primary-palette-70':  t(pp, 70),
  'primary-palette-80':  t(pp, 80),
  'primary-palette-90':  t(pp, 90),
  'primary-palette-95':  t(pp, 95),
  'primary-palette-99':  t(pp, 99),

  // Neutral palette tones
  'neutral-palette-4':   t(np, 4),
  'neutral-palette-6':   t(np, 6),
  'neutral-palette-10':  t(np, 10),
  'neutral-palette-12':  t(np, 12),
  'neutral-palette-17':  t(np, 17),
  'neutral-palette-20':  t(np, 20),
  'neutral-palette-22':  t(np, 22),
  'neutral-palette-24':  t(np, 24),
  'neutral-palette-87':  t(np, 87),
  'neutral-palette-90':  t(np, 90),
  'neutral-palette-92':  t(np, 92),
  'neutral-palette-95':  t(np, 95),
  'neutral-palette-99':  t(np, 99),
}

// ── Print CSS variables ──────────────────────────────────────────────────
console.log(`/* ================================================================
 * dgraph.ai M3 HCT-Generated Palette
 * Seed color: ${seeds.primary} (electric indigo)
 * Generated by: scripts/generate-palette.mjs
 * DO NOT EDIT MANUALLY — regenerate with: node scripts/generate-palette.mjs
 * ================================================================ */

:root {`)
for (const [name, hex] of Object.entries(roles)) {
  console.log(`  --m3-${name}: ${hex};`)
}
console.log(`}`)

// Summary to stderr
console.error('\n=== dgraph.ai M3 HCT Palette ===')
for (const [name, hex] of Object.entries(roles)) {
  console.error(`  ${name.padEnd(35)} ${hex}`)
}
