apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dgraphai
  namespace: dgraphai
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"  # for long indexing WS
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.dgraphai.io
      secretName: dgraphai-tls
  rules:
    - host: app.dgraphai.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dgraphai-api
                port:
                  number: 80
